### ISSUE TITLE
Bintray Version

### ISSUE THREAD

**Issue by ghost** [h2non/node-bintray#6]
Hi, quick question.

This repo is quite old and it looks like there hasn't been any activity recently. This tool supports V1. 

What is the current Bintray API version? 

I have checked the docs and I can't find a single page, declaring what the current version actually is.

Thanks

**Comment by h2non** [comment]
Version 1, since it was written more than 4 years ago.

**Comment by ghost** [comment]
Sorry I think I might not have expressed my question very clearly.

What is the current version of the [Bintray API](https://bintray.com/docs/api/)

**Comment by h2non** [comment]
Bintray API version is `1.0`, according to its documentation. Package API client version is `1.0`:
https://github.com/h2non/node-bintray/blob/master/src/bintray.coffee#L10

It should work, but it looks like more API feature were added these years, so not all the programmatic API capabilities are available in the current package.

**Comment by ghost** [comment]
Great. Thanks for your time. 

We may use your work, [here](https://github.com/blender/Rome/issues/120#issuecomment-390166552).
